version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  flask:
    build: .
    container_name: flask-app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis